"""create initial tables

Revision ID: 8369a7b4a88c
Revises: 
Create Date: 2026-09-23 21:33:20.886476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8369a7b4a88c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('raw_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraping_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_scraped', sa.Integer(), nullable=True),
    sa.Column('total_inserted', sa.Integer(), nullable=True),
    sa.Column('total_updated', sa.Integer(), nullable=True),
    sa.Column('total_skipped', sa.Integer(), nullable=True),
    sa.Column('total_flagged', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='scrapingstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('publisher_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('e_issn', sa.String(), nullable=True),
    sa.Column('p_issn', sa.String(), nullable=True),
    sa.Column('sinta_url', sa.String(), nullable=True),
    sa.Column('current_rank', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'unverified', name='journalstatus'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_rank_histories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('journal_id', sa.BigInteger(), nullable=False),
    sa.Column('sinta_rank', sa.String(), nullable=False),
    sa.Column('accreditation_year', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_rank_histories')
    op.drop_table('journals')
    op.drop_table('scraping_logs')
    op.drop_table('publishers')
    # ### end Alembic commands ###
